version: "3.7"
services:
    deno-dev:
        build: .
        container_name: deno-dev
        ports:
            - "3000"
        volumes:
            - "./persistent:/srv/persistent"
            - "./app:/srv/app"
            - "./deno:/srv/deno"
            - "./node:/srv/node"
        stdin_open: true
        tty: true